name: 'Launch AWX/AAP Template'
description: 'Action for launching an AWX/AAP Job or Workflow Template'
author: 'Dennis Whitney'

inputs:
  controller_url:
    description: 'The URL of AWX/AAP. Type: string'
    required: true
  controller_username:
    description:
      'The username to log into the controller. One of username/password or
      token needs to be provided. Type: string'
    required: false
  controller_password:
    description:
      'The password to log into the controller. One of username/password or
      token needs to be provided. Type: string'
    required: false
  controller_token:
    description:
      'The token to authenticate to the controller. One of username/password or
      token needs to be provided. Type: string'
    required: false
  controller_timeout:
    description:
      'The timeout in milliseconds to wait for a call to the controller before
      erroring out. Type: string[integer]'
    required: false
    default: '5000'
  controller_verify_certificate:
    description:
      "Verify if the controller's certificate is valid. Type string[boolean]"
    required: false
    default: 'true'
  job_template_id:
    description:
      'The job template id. This is mutually exclusive with
      workflow_job_template_id. Type: string[integer]'
    required: false
  workflow_job_template_id:
    description:
      'The workflow job template id. This is mutually exclusive with
      job_template_id Type: string[integer]'
    required: false
  extra_vars:
    description:
      'Pass extra command line variables to the playbook. Type: string[json]'
    required: false
  inventory:
    description:
      'Select the inventory containing the hosts you want this job to manage.
      Type: string'
    required: false
  scm_branch:
    description:
      'Branch to checkout. In addition to branches, you can input tags, commit
      hashes, and arbitrary refs. Type: string'
    required: false
  limit:
    description:
      'Provide a host pattern to further constrain the list of hosts that will
      be managed or affected by the playbook. Type: string'
    required: false
  job_tags:
    description:
      'Tags are useful when you have a large playbook, and you want to run a
      specific part of a play or task. Use commas to separate multiple tags.
      Type: string'
    required: false
  skip_tags:
    description:
      'Skip tags are useful when you have a large playbook, and you want to skip
      specific parts of a play or task. Use commas to separate multiple tags.
      Type: string'
    required: false
  job_type:
    description:
      "For job templates, select run to execute the playbook. Select check to
      only check playbook syntax, test environment setup, and report problems
      without executing the playbook. Can only be one of 'run', or 'check' Type:
      string"
    required: false
  verbosity:
    description:
      'Control the level of output ansible will produce as the playbook
      executes. Can only be one of 0-5. Type: string[integer]'
    required: false
  diff_mode:
    description:
      'If enabled, show the changes made by Ansible tasks, where supported.
      Type: string[boolean]'
    required: false
  credentials:
    description:
      "Select credentials for accessing the nodes this job will be ran against.
      Specify as a list of ID's separated by commas. Type: string"
    required: false
  credential_passwords:
    description: 'Credentials Passwords. Type: string[json]'
    required: false
  execution_environment:
    description:
      'The container image to be used for execution. Specify as the ID of the
      EE. Type: string[integer]'
    required: false
  labels:
    description:
      "Optional labels that describe this job template, such as 'dev' or 'test'.
      Specify as a list of ID's separated by commas. Type: string"
    required: false
  forks:
    description:
      'The number of parallel or simultaneous processes to use while executing
      the playbook. Type: string[integer]'
    required: false
  job_slice_count:
    description:
      'Divide the work done by this job template into the specified number of
      job slices, each running the same tasks against a portion of the
      inventory. Type: string[integer]'
    required: false
  timeout:
    description:
      'The amount of time (in seconds) to run before the job is canceled. Type:
      string[integer]'
    required: false
  instance_groups:
    description:
      "Select the Instance Groups for this Job Template to run on. Specify as a
      list of ID's separated by commas. Type: string"
    required: false

runs:
  using: node20
  main: dist/index.js
